### ISSUE TITLE
The package doesn't work with more recent versions of the azure package

### ISSUE THREAD

**Issue by emadelwany** [jstott/grunt-azureblob#10]
Currently this package depends on:
"azure": ">= 0.7.2",

But the newer versions of azure have an API change that breaks it (Specifically, the method BlobService::createBlockBlobFromFile has been removed.

Last known good is azure 0.8.1.

**Comment by mwmwmw** [comment]
I downgraded back to 0.8.1 and it works. Temporary fix.

**Comment by emadelwany** [comment]
Thanks @mwmwmw
