### ISSUE TITLE
Can't load plugin

### ISSUE THREAD

**Issue by altano** [jstott/grunt-azureblob#2]
You didn't register your dependency on 'tmp' in your package.json.

Thanks for writing this and responding to my other issue so quickly, but it would be awesome if you could please do clean-room testing of your plug-in before publishing to npm (fetch the git repo and run 'npm install' and run the plugin in grunt).  All the azure grunt plug-ins on npm are completely broken :(

**Comment by jstott** [comment]
Indeed - I had the 'tmp' package in devDependencies, not dependencies.  Thank you.
