### ISSUE TITLE
Plugin doesn't work if neither maskBaseDir nor destPrefix are specified

### ISSUE THREAD

**Issue by altano** [jstott/grunt-azureblob#3]
maskBaseDir and destPrefix default to '', which is falsey (evaluates to false when implicitly converted to boolean expression), so this code doesn't set the destination:

```
  // ensure trailing slash is present in destination
  if (options.maskBaseDir) {
    destination = source.replace(options.maskBaseDir,'');
  }
```

As a result, the destination remains undefined and the azure SDK will barf with the following error:

```
>> Error processing azureblob:assets
Fatal error: Required argument blob for function createBlockBlobFromFile is not defined
Error: Required argument blob for function createBlockBlobFromFile is not defined
```

I can work around this by specifying a maskBaseDir, which I needed to do anyway.

**Comment by jstott** [comment]
Sorry for the troubles today - destination is now being defaulted to source, seems to be better in testing for maskBaseDir and destPrefix when set to ''.  Many thanks again.

**Comment by altano** [comment]
No need to apologize.  Again, thanks for the quick fixes and writing the plugin in the first place.  I'll definitely be making use of it.
