### ISSUE TITLE
[enhancement] Limiting gzip to .js and .css files doesn't make sense

### ISSUE THREAD

**Issue by altano** [jstott/grunt-azureblob#4]
A user can theoretically want anything to be gzipped.  I don't know of any restrictions on the types of files an http user-agent can accept gzip-encoded.

Since this grunt task is a multi-task, if the user wants to gzip some files and not others, they can just target *.js and *.css with the gzip option and leave it off for another target.

I don't believe it doesn't make sense to hard code this restriction.

**Comment by jstott** [comment]
Agree - updated code checked in

**Comment by altano** [comment]
Cool, thanks!

And with all of these non-backwards-compatible changes we've been making, you might want to bump the major version to prevent breaking anyone's existing code that makes use of the current options.

Thanks again for being so responsive.  This was a fun collaboration :)

**Comment by jstott** [comment]
Thank you for contributing - it's because of folks like you, this whole process works.  Your additions were fantastic.  Looking forward to the next collaboration!
